name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup NodeJS
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '12.10.x'
    - name: Run Tests
      run: |
        npm ci
        npm run generate:keys-forge
        npm test
    - name: Publish Image
      run: | 
        docker login docker.pkg.github.com -u "${GITHUB_ACTOR}" -p "${GITHUB_TOKEN}"
        docker build -t "docker.pkg.github.com/benedridge/mutual-tls/mutual-tls:latest" .
        docker push "docker.pkg.github.com/benedridge/mutual-tls/mutual-tls:latest"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
