name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout and Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: "16"
    - name: Run Tests
      run: |
        echo "node version:" && node --version
        npm ci
        npm test
    - name: Publish Image
      run: | 
        docker login docker.pkg.github.com -u "${GITHUB_ACTOR}" -p "${GITHUB_TOKEN}"
        docker build -t "docker.pkg.github.com/benedridge/mutual-tls/mutual-tls:latest" .
        docker push "docker.pkg.github.com/benedridge/mutual-tls/mutual-tls:latest"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
